"Resource/UI/WorkshopWeaponTool.res"
{
	"WeaponModTool"
	{
		"ControlName"	"Frame"
		"fieldName"		"WeaponModTool"
		"xpos"			"c-600"
		"ypos"			"c-450"
		"wide"			"1200"
		"tall"			"900"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"bgcolor_override"		"46 43 42 255"
	}

	"MainBackground"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"MainBackground"
		"xpos"			"0"
		"ypos"			"24"
		"zpos"			"-1"
		"wide"			"1200"
		"tall"			"876"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"		"46 43 42 255"
		"PaintBackgroundType"	"0"
	}

	"TitleLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TitleLabel"
		"font"			"HudFontMediumBold"
		"labelText"		"#TF_WorkshopWeaponTool_Title"
		"textAlignment"	"west"
		"xpos"			"20"
		"ypos"			"5"
		"zpos"			"1"
		"wide"			"400"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"235 226 202 255"
	}

	"CloseButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"CloseButton"
		"xpos"			"1155"
		"ypos"			"5"
		"zpos"			"2"
		"wide"			"30"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"X"
		"font"			"HudFontMediumBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"Close"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"200 187 161 255"
		"armedFgColor_override"		"255 100 100 255"
		"depressedFgColor_override"	"200 187 161 255"
		"defaultBgColor_override"	"72 67 62 255"
		"armedBgColor_override"		"120 60 60 255"
		"depressedBgColor_override"	"60 55 50 255"
	}

	"LeftPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"LeftPanel"
		"xpos"			"20"
		"ypos"			"40"
		"zpos"			"0"
		"wide"			"560"
		"tall"			"820"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"		"38 36 35 255"
		"PaintBackgroundType"	"0"
		"border"		"TFFatLineBorder"
	}

	"ModelPreviewLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ModelPreviewLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#TF_WorkshopWeaponTool_ModelPreview"
		"textAlignment"	"west"
		"xpos"			"35"
		"ypos"			"50"
		"zpos"			"1"
		"wide"			"520"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"200 187 161 255"
	}

	"ModelPreviewPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"ModelPreviewPanel"
		"xpos"			"35"
		"ypos"			"80"
		"zpos"			"1"
		"wide"			"530"
		"tall"			"620"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"		"30 28 27 255"
		"PaintBackgroundType"	"0"
		"border"		"TFFatLineBorderOpaque"
	}

	"ModelPreviewHint"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ModelPreviewHint"
		"font"			"HudFontSmall"
		"labelText"		"#TF_WorkshopWeaponTool_DragToRotate"
		"textAlignment"	"center"
		"xpos"			"35"
		"ypos"			"705"
		"zpos"			"1"
		"wide"			"530"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"150 140 120 255"
	}

	"BrowseButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"BrowseButton"
		"xpos"			"35"
		"ypos"			"735"
		"zpos"			"1"
		"wide"			"255"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_WorkshopWeaponTool_BrowseMDL"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"BrowseModel"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"200 187 161 255"
		"armedFgColor_override"		"235 226 202 255"
		"depressedFgColor_override"	"200 187 161 255"
		"defaultBgColor_override"	"72 67 62 255"
		"armedBgColor_override"		"90 83 75 255"
		"depressedBgColor_override"	"60 55 50 255"
	}

	"ResetViewButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"ResetViewButton"
		"xpos"			"310"
		"ypos"			"735"
		"zpos"			"1"
		"wide"			"255"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_WorkshopWeaponTool_ResetView"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"ResetView"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"200 187 161 255"
		"armedFgColor_override"		"235 226 202 255"
		"depressedFgColor_override"	"200 187 161 255"
		"defaultBgColor_override"	"72 67 62 255"
		"armedBgColor_override"		"90 83 75 255"
		"depressedBgColor_override"	"60 55 50 255"
	}

	"AutoRotateCheck"
	{
		"ControlName"	"CheckButton"
		"fieldName"		"AutoRotateCheck"
		"xpos"			"35"
		"ypos"			"785"
		"zpos"			"1"
		"wide"			"530"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_WorkshopWeaponTool_AutoRotate"
		"font"			"HudFontSmall"
		"textAlignment"	"west"
		"Command"		"ToggleAutoRotate"
		"fgcolor_override"	"200 187 161 255"
	}

	"RightPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"RightPanel"
		"xpos"			"600"
		"ypos"			"40"
		"zpos"			"0"
		"wide"			"580"
		"tall"			"820"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"		"38 36 35 255"
		"PaintBackgroundType"	"0"
		"border"		"TFFatLineBorder"
	}

	"WeaponSelectLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"WeaponSelectLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#TF_WorkshopWeaponTool_SelectWeapon"
		"textAlignment"	"west"
		"xpos"			"620"
		"ypos"			"50"
		"zpos"			"1"
		"wide"			"540"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"200 187 161 255"
	}

	// Weapon icon preview panel (left side of weapon selection)
	"WeaponIconPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"WeaponIconPanel"
		"xpos"			"620"
		"ypos"			"80"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"	"30 28 27 255"
		"PaintBackgroundType"	"0"
		"border"		"TFFatLineBorderOpaque"
	}

	// Search bar for filtering weapons
	"WeaponSearchEntry"
	{
		"ControlName"	"TextEntry"
		"fieldName"		"WeaponSearchEntry"
		"xpos"			"730"
		"ypos"			"80"
		"zpos"			"1"
		"wide"			"430"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"1"
		"font"			"HudFontSmall"
		"fgcolor_override"	"200 187 161 255"
		"bgcolor_override"	"60 55 50 255"
		"border"		"TFFatLineBorder"
	}

	// Slot filter combo
	"SlotFilterLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SlotFilterLabel"
		"font"			"HudFontSmall"
		"labelText"		"Slot:"
		"textAlignment"	"east"
		"xpos"			"730"
		"ypos"			"110"
		"zpos"			"1"
		"wide"			"30"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"200 187 161 255"
	}

	"SlotFilterCombo"
	{
		"ControlName"	"ComboBox"
		"fieldName"		"SlotFilterCombo"
		"xpos"			"765"
		"ypos"			"110"
		"zpos"			"1"
		"wide"			"130"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"textHidden"	"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"	"0"
		"unicode"		"0"
		"font"			"HudFontSmall"
		"fgcolor_override"	"200 187 161 255"
		"bgcolor_override"	"60 55 50 255"
		"border"		"TFFatLineBorder"
	}

	// Class filter combo (with class icons label)
	"ClassFilterLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ClassFilterLabel"
		"font"			"HudFontSmall"
		"labelText"		"Class:"
		"textAlignment"	"east"
		"xpos"			"900"
		"ypos"			"110"
		"zpos"			"1"
		"wide"			"40"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"200 187 161 255"
	}

	"ClassFilterCombo"
	{
		"ControlName"	"ComboBox"
		"fieldName"		"ClassFilterCombo"
		"xpos"			"945"
		"ypos"			"110"
		"zpos"			"1"
		"wide"			"215"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"textHidden"	"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"	"0"
		"unicode"		"0"
		"font"			"HudFontSmall"
		"fgcolor_override"	"200 187 161 255"
		"bgcolor_override"	"60 55 50 255"
		"border"		"TFFatLineBorder"
	}

	"WeaponCombo"
	{
		"ControlName"	"ComboBox"
		"fieldName"		"WeaponCombo"
		"xpos"			"730"
		"ypos"			"145"
		"zpos"			"1"
		"wide"			"430"
		"tall"			"30"
		"visible"		"1"
		"enabled"		"1"
		"textHidden"	"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"	"0"
		"unicode"		"0"
		"font"			"HudFontSmall"
		"fgcolor_override"	"200 187 161 255"
		"bgcolor_override"	"60 55 50 255"
		"border"		"TFFatLineBorder"
	}

	"AddWeaponButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"AddWeaponButton"
		"xpos"			"620"
		"ypos"			"185"
		"zpos"			"1"
		"wide"			"540"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_WorkshopWeaponTool_AddReplacement"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"AddWeapon"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"200 187 161 255"
		"armedFgColor_override"		"235 226 202 255"
		"depressedFgColor_override"	"200 187 161 255"
		"defaultBgColor_override"	"72 67 62 255"
		"armedBgColor_override"		"90 83 75 255"
		"depressedBgColor_override"	"60 55 50 255"
	}

	"ReplacementListLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ReplacementListLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#TF_WorkshopWeaponTool_ReplacementList"
		"textAlignment"	"west"
		"xpos"			"620"
		"ypos"			"230"
		"zpos"			"1"
		"wide"			"540"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"200 187 161 255"
	}

	"ReplacementList"
	{
		"ControlName"	"ListPanel"
		"fieldName"		"ReplacementList"
		"xpos"			"620"
		"ypos"			"260"
		"zpos"			"1"
		"wide"			"540"
		"tall"			"340"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"font"			"HudFontSmall"
		"fgcolor_override"	"200 187 161 255"
		"bgcolor_override"	"30 28 27 255"
		"border"		"TFFatLineBorderOpaque"
	}

	"OutputDirLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"OutputDirLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#TF_WorkshopWeaponTool_OutputDir"
		"textAlignment"	"west"
		"xpos"			"620"
		"ypos"			"610"
		"zpos"			"1"
		"wide"			"540"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"200 187 161 255"
	}

	"OutputPathEntry"
	{
		"ControlName"	"TextEntry"
		"fieldName"		"OutputPathEntry"
		"xpos"			"620"
		"ypos"			"640"
		"zpos"			"1"
		"wide"			"430"
		"tall"			"30"
		"visible"		"1"
		"enabled"		"1"
		"textHidden"	"0"
		"editable"		"0"
		"maxchars"		"-1"
		"font"			"HudFontSmall"
		"fgcolor_override"	"200 187 161 255"
		"bgcolor_override"	"30 28 27 255"
		"border"		"TFFatLineBorder"
	}

	"BrowseOutputButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"BrowseOutputButton"
		"xpos"			"1060"
		"ypos"			"640"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_WorkshopWeaponTool_Browse"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"BrowseOutput"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"200 187 161 255"
		"armedFgColor_override"		"235 226 202 255"
		"depressedFgColor_override"	"200 187 161 255"
		"defaultBgColor_override"	"72 67 62 255"
		"armedBgColor_override"		"90 83 75 255"
		"depressedBgColor_override"	"60 55 50 255"
	}

	"RemoveWeaponButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"RemoveWeaponButton"
		"xpos"			"620"
		"ypos"			"710"
		"zpos"			"1"
		"wide"			"260"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_WorkshopWeaponTool_RemoveSelected"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"RemoveWeapon"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"200 187 161 255"
		"armedFgColor_override"		"235 226 202 255"
		"depressedFgColor_override"	"200 187 161 255"
		"defaultBgColor_override"	"72 67 62 255"
		"armedBgColor_override"		"90 83 75 255"
		"depressedBgColor_override"	"60 55 50 255"
	}

	"ClearListButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"ClearListButton"
		"xpos"			"900"
		"ypos"			"710"
		"zpos"			"1"
		"wide"			"260"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_WorkshopWeaponTool_ClearAll"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"ClearList"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"200 187 161 255"
		"armedFgColor_override"		"235 226 202 255"
		"depressedFgColor_override"	"200 187 161 255"
		"defaultBgColor_override"	"72 67 62 255"
		"armedBgColor_override"		"90 83 75 255"
		"depressedBgColor_override"	"60 55 50 255"
	}

	"Separator"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"Separator"
		"xpos"			"620"
		"ypos"			"760"
		"zpos"			"1"
		"wide"			"540"
		"tall"			"2"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"72 67 62 255"
		"scaleImage"	"1"
	}

	"CreateModButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"CreateModButton"
		"xpos"			"620"
		"ypos"			"775"
		"zpos"			"1"
		"wide"			"540"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_WorkshopWeaponTool_CreateMod"
		"font"			"HudFontMediumBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"CreateMod"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"border_default"	"TFFatLineBorder"
		"border_armed"		"TFFatLineBorderOpaque"
		"paintbackground"	"1"
		"defaultFgColor_override"	"235 226 202 255"
		"armedFgColor_override"		"255 255 255 255"
		"depressedFgColor_override"	"235 226 202 255"
		"defaultBgColor_override"	"85 118 70 255"
		"armedBgColor_override"		"105 138 90 255"
		"depressedBgColor_override"	"75 108 60 255"
	}

	"StatusLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"StatusLabel"
		"font"			"HudFontSmall"
		"labelText"		""
		"textAlignment"	"center"
		"xpos"			"35"
		"ypos"			"820"
		"zpos"			"1"
		"wide"			"530"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override"	"150 140 120 255"
	}
}
