#!/bin/bash

set -euo pipefail

script=$(readlink -f -- "$0")
pushd "$(dirname -- "$script")" > /dev/null

source sdk_container
run_in_sniper "$@"

if [ $# -eq 0 ]; then
    export VPC_NINJA_BUILD_MODE="release"     
else
    if [[ "$1" == "debug" ]]; then
        export VPC_NINJA_BUILD_MODE="debug"
    elif [[ "$1" == "release" ]]; then
        export VPC_NINJA_BUILD_MODE="release"
    else
        echo "Usage: $0 [debug|release]"
        exit 1
    fi
fi

solution_out="_vpc_/ninja/sdk_everything_$VPC_NINJA_BUILD_MODE"

if [[ ! -e "$solution_out.ninja" ]]; then
    devtools/bin/vpc /tf /linux64 /ninja /define:SOURCESDK /define:TF_RAID_MODE /define:SDK_TEMP_PATCH +everything /mksln "$solution_out"

    # Generate compile commands.
    ninja -f "$solution_out.ninja" -t compdb > compile_commands.json
    # Remove some unsupported clang commands.
    sed -i 's/-fpredictive-commoning//g; s/-fvar-tracking-assignments//g' compile_commands.json
    sed -i 's|/bf2/src|.|g' compile_commands.json
fi

# Patch ninja file to use ccache if available
if command -v ccache &> /dev/null; then
    echo "Patching ninja file to use ccache..."
    sed -i 's|command = x86_64-linux-gnu-gcc |command = ccache x86_64-linux-gnu-gcc |g' "$solution_out.ninja"
    sed -i 's|command = x86_64-linux-gnu-g++ |command = ccache x86_64-linux-gnu-g++ |g' "$solution_out.ninja"
fi

ninja -f "$solution_out.ninja" -j$(nproc)

popd
